### ISSUE TITLE
C/C++ parens and brace marks are not highlighted like Borland C++ do 

### ISSUE THREAD

**Issue by skywind3000** [letorbi/vim-colors-modern-borland#1]
Love this theme very much, but if it would be flawless if can step a little further.

I found some difference with the original Borland C++ 3.1 theme:

![Dos](https://github.com/letorbi/vim-colors-modern-borland/assets/3035071/ed018ca5-07ca-44cc-adff-10fe158f149e)

See the parens and braces/brackets, they are highlighted as "white" while this repos doesn't:

![图片](https://github.com/letorbi/vim-colors-modern-borland/assets/3035071/042138eb-0526-41b9-b4bf-fda3e76554f5)

The parens/braces/brackets are more important than the other syntax elements because they can indicate program structure,
So, highlighting them like the original Borland C++ 3.1 does will improve the visibility and make my source code more readable.

**Comment by letorbi** [comment]
Thank you for the hint. I tried to resemble the look of Borland Pascal 7.0, which does not highlight brackets (see screenshot below), but you are right when you say that highlighted brackets improve readability. Maybe Borland Pascal does not highlight them because Pascal does not use them as block-markers...

![5b656ffd6bc13a78e93e35f5a76ef847874d35fa6c6933d8202bf666dd267518](https://github.com/letorbi/vim-colors-modern-borland/assets/1268015/0f1a8d9b-4d46-4d96-8f20-09ffc3a16089)

Anyway, I think it makes sense to adapt the theme to the look of Borland C++ since a lot of modern languages use a C-like syntax.

**Comment by letorbi** [comment]
The issue should be fixed with d9d13900d5aadf6b4df17b3f7d5eb4d9d11a4caf. Please reopen it, if you think I've missed something.

**Comment by skywind3000** [comment]
Thanks
